version: '3'

services:
    applicationtest:
        image: applicationtest
        build:
            context: .
        ports: 
            - "8080:80"
        networks: 
            - app-network
        depends_on:
            - "cassandra"

    cassandra:
        image: cassandra
        ports:
            - "9042:9042" 
        networks: 
            - app-network

networks: 
     app-network:
         driver: bridge